name: Install Linux dependencies
description: Installs Linux dependencies for Bevy
runs:
  using: composite
  steps:
    - name: Install Linux dependencies
      shell: bash
      run: >
        sudo apt-get update

        sudo apt-get install --no-install-recommends
        libasound2-dev
        libudev-dev
