name: update deps
run-name: ${{ github.actor }} running update
on:
  push:
    - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  NIGHTLY_TOOLCHAIN: nightly
  RUSTFLAGS: "-D warning"
  BINSTALL_VERSION: "v1.12.3"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps
      - name: Update
        run: cargo update
      - name: Build
        id: build
        run: cargo build
        continue-on-error: true
        env:
          RUSTFLAGS: "-C debuginfo=0 -D warnings"
      - name: Commit
        if: steps.build.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: Cargo.lock
          DESTINATION_BRANCH: main
        run: |
          export TODAY=$( date -u '+%Y-%m-%d' )
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content=@<( base64 -i $FILE_TO_COMMIT ) \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"
