name: build
run-name: ${{ github.actor }} running build
on: [push]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  NIGHTLY_TOOLCHAIN: nightly
  RUSTFLAGS: "-D warning"
  BINSTALL_VERSION: "v1.12.3"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps
      - name: Build
        run: cargo build
        env:
          RUSTFLAGS: "-C debuginfo=0 -D warnings"
